name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

              - uses: actions/checkout@v3
              - name: executando docker
                run: docker run docker/whalesay cowsay TESTANDO ATV  MAIS UM UPDATE/FELIZ EM TER CONSEGUIDO :D

              - name: Run a multi-line script
                run:
                   echo Add other actions to bluid,
                   echo teste, and deploy your project.
